# Generated by Django 3.2.25 on 2024-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
