# Generated by Django 3.2.25 on 2024-05-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_slug'),
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='games.game'),
        ),
    ]
