# Generated by Django 5.0.7 on 2024-07-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_xcacib', upload_to='images/'),
        ),
    ]
