# Generated by Django 5.0.7 on 2024-07-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../gg_default_profile_jzmgfi', upload_to='images/'),
        ),
    ]
