# Generated by Django 4.2 on 2024-08-17 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_remove_game_slug'),
        ('saved_games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedgame',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='savedgame',
            unique_together={('owner', 'game')},
        ),
    ]
