# Generated by Django 3.2.25 on 2024-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'Role-Playing Game'), ('Strategy', 'Strategy'), ('Simulation', 'Simulation'), ('Sports', 'Sports')], max_length=50)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS4', 'PlayStation 4'), ('XBOX', 'Xbox One'), ('SWITCH', 'Nintendo Switch')], max_length=50)),
                ('average_star_rating', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('title', 'developer', 'genre', 'platform')},
            },
        ),
    ]
