# Generated by Django 5.0.7 on 2024-07-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_multiplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='../gg_default_new_game_hiawpf', upload_to='images/'),
        ),
    ]
