# Generated by Django 5.0.7 on 2024-08-02 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
