# Generated by Django 4.2 on 2024-08-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
