# Generated by Django 5.0.7 on 2024-08-02 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
